version: '3'
services:
  clawer:
    build: .
    environment:
    - http_proxy=http://192.168.1.100:8081
    - https_proxy=http://192.168.1.100:8081
    command:
    - '6'
    working_dir: /workspace
    volumes:
    - ./:/workspace
